project_id = "iomeddeasarntjhqzndu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "https://maku.travel"
additional_redirect_urls = ["https://maku.travel"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[edge_functions]
enabled = true
port = 54330

[functions.create-booking]
verify_jwt = true

[functions.create-booking-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.unified-search]
verify_jwt = false

[functions.amadeus-flight-search]
verify_jwt = false

[functions.amadeus-hotel-search]
verify_jwt = false

[functions.amadeus-hotel-list]
verify_jwt = false

[functions.amadeus-hotel-offers]
verify_jwt = false

[functions.amadeus-hotel-details]
verify_jwt = false

[functions.amadeus-hotel-photos]
verify_jwt = false

[functions.amadeus-hotel-ratings]
verify_jwt = false

[functions.amadeus-hotel-booking]
verify_jwt = true

[functions.amadeus-flight-booking]
verify_jwt = true

[functions.amadeus-flight-offers]
verify_jwt = false

[functions.amadeus-flight-price-confirm]
verify_jwt = true

[functions.amadeus-price-confirm]
verify_jwt = true

[functions.amadeus-seat-map]
verify_jwt = false

[functions.amadeus-locations-autocomplete]
verify_jwt = false

[functions.amadeus-hotel-autocomplete]
verify_jwt = false

[functions.amadeus-points-of-interest]
verify_jwt = false

[functions.amadeus-safe-place]
verify_jwt = false

[functions.amadeus-activity-search]
verify_jwt = false

[functions.amadeus-car-search]
verify_jwt = false

[functions.amadeus-transfer-search]
verify_jwt = false

[functions.amadeus-flight-inspiration]
verify_jwt = false

[functions.amadeus-health]
verify_jwt = false

[functions.hotelbeds-search]
verify_jwt = false

[functions.hotelbeds-autocomplete]
verify_jwt = false

[functions.activity-search]
verify_jwt = false

[functions.travelport-search]
verify_jwt = false

[functions.sabre-flight-search]
verify_jwt = false

[functions.sabre-hotel-search]
verify_jwt = false

[functions.sabre-locations-autocomplete]
verify_jwt = false

[functions.sabre-flight-offers]
verify_jwt = false

[functions.verify-booking-payment]
verify_jwt = true

[functions.verify-partner-payment]
verify_jwt = true

[functions.validate-passport]
verify_jwt = true

[functions.create-card-payment-intent]
verify_jwt = false

[functions.create-hotel-booking]
verify_jwt = true

[functions.create-partner-checkout]
verify_jwt = true

[functions.create-gift-card]
verify_jwt = false

[functions.validate-gift-card]
verify_jwt = false

[functions.send-gift-card-email]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.guest-booking-lookup]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false

[functions.security-cleanup]
verify_jwt = false

[functions.rate-limiter]
verify_jwt = false

[functions.ai-training-anonymizer]
verify_jwt = false

[functions.generate-offers]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.performance-monitor]
verify_jwt = false

[functions.create-activity-booking]
verify_jwt = true

[functions.test-deployment]
verify_jwt = false

[functions.deployment-validator]
verify_jwt = false

[functions.critical-debug]
verify_jwt = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.comprehensive-health-monitor]
verify_jwt = false

[functions.booking-integrity-manager]
verify_jwt = true

[functions.enhanced-stripe-webhook]
verify_jwt = false

[functions.provider-rotation]
verify_jwt = false

[functions.hotelbeds-activities]
verify_jwt = false

[functions.credential-test]
verify_jwt = false