project_id = "iomeddeasarntjhqzndu"

[functions.admin-metrics]
verify_jwt = true

[functions.production-readiness]
verify_jwt = true

[functions.unified-health-monitor]
verify_jwt = true

[functions.provider-quota-monitor]
verify_jwt = true

[functions.emergency-system-recovery]
verify_jwt = true

[functions.critical-booking-alerts]
verify_jwt = true

[functions.bulk-booking-operations]
verify_jwt = true

[functions.automated-recovery-scheduler]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "https://maku.travel"
additional_redirect_urls = ["https://maku.travel"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[edge_functions]
enabled = true
port = 54330

[functions.create-booking]
verify_jwt = true

[functions.create-booking-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = true

[functions.unified-search]
verify_jwt = true

[functions.amadeus-flight-search]
verify_jwt = true

[functions.amadeus-hotel-search]
verify_jwt = true

[functions.amadeus-hotel-list]
verify_jwt = true

[functions.amadeus-hotel-offers]
verify_jwt = true

[functions.amadeus-hotel-details]
verify_jwt = true

[functions.amadeus-hotel-photos]
verify_jwt = true

[functions.amadeus-hotel-ratings]
verify_jwt = true

[functions.amadeus-hotel-booking]
verify_jwt = true

[functions.amadeus-flight-booking]
verify_jwt = true

[functions.amadeus-flight-offers]
verify_jwt = true

[functions.amadeus-flight-price-confirm]
verify_jwt = true

[functions.amadeus-price-confirm]
verify_jwt = true

[functions.amadeus-seat-map]
verify_jwt = true

[functions.amadeus-locations-autocomplete]
verify_jwt = true

[functions.amadeus-hotel-autocomplete]
verify_jwt = true

[functions.amadeus-points-of-interest]
verify_jwt = true

[functions.amadeus-safe-place]
verify_jwt = true

[functions.amadeus-activity-search]
verify_jwt = true

[functions.amadeus-car-search]
verify_jwt = true

[functions.amadeus-transfer-search]
verify_jwt = true

[functions.amadeus-flight-inspiration]
verify_jwt = true

[functions.amadeus-health]
verify_jwt = true

[functions.hotelbeds-search]
verify_jwt = true

[functions.hotelbeds-autocomplete]
verify_jwt = true

[functions.activity-search]
verify_jwt = true

[functions.travelport-search]
verify_jwt = true

[functions.sabre-flight-search]
verify_jwt = true

[functions.sabre-hotel-search]
verify_jwt = true

[functions.sabre-locations-autocomplete]
verify_jwt = true

[functions.sabre-flight-offers]
verify_jwt = true

[functions.verify-booking-payment]
verify_jwt = true

[functions.verify-partner-payment]
verify_jwt = true

[functions.validate-passport]
verify_jwt = true

[functions.create-card-payment-intent]
verify_jwt = true

[functions.create-hotel-booking]
verify_jwt = true

[functions.create-partner-checkout]
verify_jwt = true

[functions.create-gift-card]
verify_jwt = true

[functions.validate-gift-card]
verify_jwt = true

[functions.send-gift-card-email]
verify_jwt = true

[functions.send-booking-confirmation]
verify_jwt = true

[functions.guest-booking-lookup]
verify_jwt = true

[functions.get-stripe-publishable-key]
verify_jwt = true

[functions.security-cleanup]
verify_jwt = true

[functions.rate-limiter]
verify_jwt = true

[functions.ai-training-anonymizer]
verify_jwt = true

[functions.generate-offers]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.performance-monitor]
verify_jwt = true

[functions.create-activity-booking]
verify_jwt = true

[functions.test-deployment]
verify_jwt = true

[functions.deployment-validator]
verify_jwt = true

[functions.critical-debug]
verify_jwt = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.comprehensive-health-monitor]
verify_jwt = true

[functions.configure-auth-security]
verify_jwt = true

[functions.production-booking-manager]
verify_jwt = true

[functions.booking-integrity-manager]
verify_jwt = true

[functions.enhanced-stripe-webhook]
verify_jwt = true

[functions.provider-rotation]
verify_jwt = true

[functions.hotelbeds-activities]
verify_jwt = true

[functions.credential-test]
verify_jwt = true

[functions.hotelbeds-checkrates]
verify_jwt = true

[functions.hotelbeds-booking]
verify_jwt = true

[functions.hotelbeds-reconfirmation]
verify_jwt = true

[functions.hotelbeds-content]
verify_jwt = true

[functions.hotelbeds-monitoring]
verify_jwt = true

[functions.hotelbeds-cancel-booking]
verify_jwt = true

[functions.environment-config]
verify_jwt = true

[functions.error-tracking]
verify_jwt = true

[functions.log-system-event]
verify_jwt = true

[functions.test-provider-rotation]
verify_jwt = true

[functions.hotelbeds-credential-test]
verify_jwt = true

[functions.sabre-flight-booking]
verify_jwt = true

[functions.sabre-pnr-management]
verify_jwt = true

[functions.sabre-seat-selection]
verify_jwt = true

[functions.sabre-air-extras]
verify_jwt = true

[functions.sabre-travel-alerts]
verify_jwt = true

[functions.sabre-flight-exchange]
verify_jwt = true

[functions.sabre-flight-price]
verify_jwt = true

[functions.sabre-air-ticket]
verify_jwt = true

[functions.sabre-activities]
verify_jwt = true

[functions.sabre-hotel-content]
verify_jwt = true

[functions.hotelbeds-image-content]
verify_jwt = true

[functions.amadeus-order-create]
verify_jwt = true

[functions.comprehensive-testing]
verify_jwt = true

[functions.track-performance]
verify_jwt = true

[functions.enhanced-provider-health]
verify_jwt = true

[functions.test-infrastructure-activation]
verify_jwt = true

[functions.self-healing-executor]
verify_jwt = true

[functions.advanced-alerting]
verify_jwt = true

[functions.performance-optimizer]
verify_jwt = true

[functions.security-hardening]
verify_jwt = true

[functions.business-intelligence]
verify_jwt = true

[functions.scalability-manager]
verify_jwt = true

[functions.gpt-bot-connector]
verify_jwt = false

[functions.gpt-workflow-orchestrator]
verify_jwt = false

[functions.maku-bot]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false


[functions.conversational-ai]
verify_jwt = false

[functions.dialogflow-cx-webhook]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = true

[functions.google-flight-search]
verify_jwt = true

[functions.google-hotel-search]
verify_jwt = true

[functions.google-activity-search]
verify_jwt = true

[functions.duffel-flight-search]
verify_jwt = true

[functions.duffel-order-create]
verify_jwt = true

[functions.duffel-webhook]
verify_jwt = false
