[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://maku.travel/*"
  to = "https://www.maku.travel/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
