#!/bin/bash
# Railway Environment Variables Export
# Copy-paste these into Railway Dashboard → Variables → RAW Editor

cat << 'RAILWAY_ENV'
# Core Configuration
ENVIRONMENT=production
MONGO_URL=${{MONGO_URL}}
DB_NAME=maku_production
CORS_ORIGINS=${{NETLIFY_URL}}

# Supabase Configuration
SUPABASE_URL=https://iomeddeasarntjhqzndu.supabase.co
SUPABASE_SERVICE_ROLE_KEY=${{SUPABASE_SERVICE_ROLE_KEY}}
SUPABASE_ANON_KEY=${{SUPABASE_ANON_KEY}}

# Provider API Keys - PRODUCTION
SABRE_CLIENT_ID=${{SABRE_CLIENT_ID}}
SABRE_CLIENT_SECRET=${{SABRE_CLIENT_SECRET}}
SABRE_API_BASE=https://api.sabre.com
SABRE_ENV=production

HOTELBEDS_API_KEY=${{HOTELBEDS_API_KEY}}
HOTELBEDS_API_SECRET=${{HOTELBEDS_API_SECRET}}
HOTELBEDS_API_BASE=https://api.hotelbeds.com
HOTELBEDS_ENV=production

AMADEUS_API_KEY=${{AMADEUS_API_KEY}}
AMADEUS_API_SECRET=${{AMADEUS_API_SECRET}}
AMADEUS_API_BASE=https://api.amadeus.com
AMADEUS_ENV=production

VIATOR_API_KEY=${{VIATOR_API_KEY}}
GETYOURGUIDE_API_KEY=${{GETYOURGUIDE_API_KEY}}
EXPEDIA_API_KEY=${{EXPEDIA_API_KEY}}
EXPEDIA_API_SECRET=${{EXPEDIA_API_SECRET}}

# OpenAI
OPENAI_API_KEY=${{OPENAI_API_KEY}}
OPENAI_MODEL=gpt-4o
SMART_DREAMS_MODEL=gpt-4o
TRAVEL_DNA_MODEL=o1
RECOMMENDATIONS_MODEL=gpt-4o-mini

# Emergent LLM Key
EMERGENT_LLM_KEY=${{EMERGENT_LLM_KEY}}

# Provider Configuration
PROVIDER_ROTATION_ENABLED=true
PROVIDER_ECO_PRIORITY=true
PROVIDER_LOCAL_FIRST=true
PROVIDER_HEALTH_CHECK_INTERVAL=300
PROVIDER_MAX_RETRIES=3
PROVIDER_TIMEOUT_MS=30000
PROVIDER_CACHE_TTL=3600

# Blockchain Configuration
BLOCKCHAIN_MODE=production
POLYGON_RPC_URL=https://polygon-rpc.com
MAKU_TOKEN_ADDRESS=${{MAKU_TOKEN_ADDRESS}}
MAKU_NFT_ADDRESS=${{MAKU_NFT_ADDRESS}}
BLOCKCHAIN_PRIVATE_KEY=${{BLOCKCHAIN_PRIVATE_KEY}}

# Security
JWT_SECRET=${{JWT_SECRET}}
ENCRYPTION_KEY=${{ENCRYPTION_KEY}}
SECRET_KEY=${{SECRET_KEY}}

# Cost Management
DAILY_COST_THRESHOLD=100
USER_DAILY_THRESHOLD=10

# Rollout
CHATGPT_PRO_PHASE=production

# Development Flags
USE_EMERGENT_AI=true
USE_FREE_AI=false
DEVELOPMENT_MODE=false
RAILWAY_ENV

echo "✅ Copy the above and paste into Railway Dashboard → Variables → RAW Editor"
echo "📝 Replace \${{VARIABLE}} placeholders with actual values"
