-- Insert workflow templates
INSERT INTO orchestration_workflows (name, description, category, template_type, workflow_data, is_active, created_by) VALUES
('Customer Onboarding Flow', 'Automated customer onboarding with welcome sequences and account setup', 'customer_journey', 'system', '{"nodes": [{"id": "trigger", "type": "trigger", "position": {"x": 100, "y": 100}, "data": {"trigger": "New Customer Registration"}}, {"id": "welcome", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"agentId": "welcome-agent", "agentName": "Welcome Agent", "status": "idle", "config": {"task": "send_welcome_email"}, "performance": {"successRate": 95, "avgResponseTime": 250}}}], "edges": [{"id": "e1", "source": "trigger", "target": "welcome", "markerEnd": {"type": "arrowclosed"}}]}', true, '00000000-0000-0000-0000-000000000000'),

('Lead Qualification Pipeline', 'Multi-stage lead qualification with scoring and routing', 'customer_journey', 'system', '{"nodes": [{"id": "trigger", "type": "trigger", "position": {"x": 100, "y": 100}, "data": {"trigger": "New Lead Capture"}}, {"id": "qualifier", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"agentId": "qualifier-agent", "agentName": "Lead Qualifier", "status": "idle", "config": {"task": "qualify_lead"}, "performance": {"successRate": 88, "avgResponseTime": 180}}}], "edges": [{"id": "e1", "source": "trigger", "target": "qualifier", "markerEnd": {"type": "arrowclosed"}}]}', true, '00000000-0000-0000-0000-000000000000'),

('Order Processing Workflow', 'End-to-end order processing from payment to fulfillment', 'operations', 'system', '{"nodes": [{"id": "trigger", "type": "trigger", "position": {"x": 100, "y": 100}, "data": {"trigger": "Order Received"}}, {"id": "processor", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"agentId": "order-processor", "agentName": "Order Processor", "status": "idle", "config": {"task": "process_order"}, "performance": {"successRate": 99, "avgResponseTime": 120}}}], "edges": [{"id": "e1", "source": "trigger", "target": "processor", "markerEnd": {"type": "arrowclosed"}}]}', true, '00000000-0000-0000-0000-000000000000'),

('Support Ticket Routing', 'Intelligent support ticket classification and routing', 'support_quality', 'system', '{"nodes": [{"id": "trigger", "type": "trigger", "position": {"x": 100, "y": 100}, "data": {"trigger": "Support Ticket Created"}}, {"id": "classifier", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"agentId": "ticket-classifier", "agentName": "Ticket Classifier", "status": "idle", "config": {"task": "classify_ticket"}, "performance": {"successRate": 92, "avgResponseTime": 95}}}], "edges": [{"id": "e1", "source": "trigger", "target": "classifier", "markerEnd": {"type": "arrowclosed"}}]}', true, '00000000-0000-0000-0000-000000000000'),

('Content Moderation Pipeline', 'Automated content review and moderation workflow', 'support_quality', 'system', '{"nodes": [{"id": "trigger", "type": "trigger", "position": {"x": 100, "y": 100}, "data": {"trigger": "Content Submitted"}}, {"id": "moderator", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"agentId": "content-moderator", "agentName": "Content Moderator", "status": "idle", "config": {"task": "moderate_content"}, "performance": {"successRate": 96, "avgResponseTime": 200}}}], "edges": [{"id": "e1", "source": "trigger", "target": "moderator", "markerEnd": {"type": "arrowclosed"}}]}', true, '00000000-0000-0000-0000-000000000000'),

('Campaign Management Flow', 'Multi-channel marketing campaign orchestration', 'marketing', 'system', '{"nodes": [{"id": "trigger", "type": "trigger", "position": {"x": 100, "y": 100}, "data": {"trigger": "Campaign Launch"}}, {"id": "manager", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"agentId": "campaign-manager", "agentName": "Campaign Manager", "status": "idle", "config": {"task": "manage_campaign"}, "performance": {"successRate": 89, "avgResponseTime": 300}}}], "edges": [{"id": "e1", "source": "trigger", "target": "manager", "markerEnd": {"type": "arrowclosed"}}]}', true, '00000000-0000-0000-0000-000000000000'),

('Performance Analytics Pipeline', 'Real-time performance data collection and analysis', 'analytics', 'system', '{"nodes": [{"id": "trigger", "type": "trigger", "position": {"x": 100, "y": 100}, "data": {"trigger": "Data Collection Event"}}, {"id": "analyzer", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"agentId": "data-analyzer", "agentName": "Data Analyzer", "status": "idle", "config": {"task": "analyze_performance"}, "performance": {"successRate": 94, "avgResponseTime": 150}}}], "edges": [{"id": "e1", "source": "trigger", "target": "analyzer", "markerEnd": {"type": "arrowclosed"}}]}', true, '00000000-0000-0000-0000-000000000000'),

('Compliance Monitoring Workflow', 'Automated compliance checking and reporting', 'compliance', 'system', '{"nodes": [{"id": "trigger", "type": "trigger", "position": {"x": 100, "y": 100}, "data": {"trigger": "Compliance Check Required"}}, {"id": "monitor", "type": "agent", "position": {"x": 300, "y": 100}, "data": {"agentId": "compliance-monitor", "agentName": "Compliance Monitor", "status": "idle", "config": {"task": "check_compliance"}, "performance": {"successRate": 98, "avgResponseTime": 180}}}], "edges": [{"id": "e1", "source": "trigger", "target": "monitor", "markerEnd": {"type": "arrowclosed"}}]}', true, '00000000-0000-0000-0000-000000000000');